issue_tracker/issue_tracker/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('accounts/', include('accounts.urls')),
]

issue_tracker/webapp/urls.py
from django.urls import path
from .views import TaskListView, TaskDetailView, TaskCreateView, TaskUpdateView, TaskDeleteView
from .views.projects import ProjectListView, ProjectDetailView, ProjectCreateView, ProjectUpdateView, ProjectDeleteView

app_name = 'webapp'

urlpatterns = [
    path('project/<int:pk>/task/add/', TaskCreateView.as_view(), name='add_task'),
    path('task/<int:pk>/', TaskDetailView.as_view(), name='detail_task'),
    path('task/<int:pk>/update/', TaskUpdateView.as_view(), name='update_task'),
    path('task/<int:pk>/delete/', TaskDeleteView.as_view(), name='delete_task'),

    path('', ProjectListView.as_view(), name='project_list'),
    path('project/<int:pk>/', ProjectDetailView.as_view(), name='project_detail'),
    path('project/add/', ProjectCreateView.as_view(), name='project_add'),
    path('project/<int:pk>/update/', ProjectUpdateView.as_view(), name='project_update'),
    path('project/<int:pk>/delete/', ProjectDeleteView.as_view(), name='project_delete')
]

issue_tracker/webapp/models.py
from django.db import models


class Status(models.Model):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Statuses'


class Type(models.Model):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name


class Task(models.Model):
    summary = models.CharField(max_length=100)
    description = models.TextField(blank=True, null=True)
    status = models.ForeignKey(Status, on_delete=models.PROTECT)
    type = models.ManyToManyField(
        Type,
        related_name="tasks",
        verbose_name="Типы",
        blank=True,
        through='TaskType',
        through_fields=("task", "type"),
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.summary

    class Meta:
        verbose_name = 'Task'
        verbose_name_plural = 'Tasks'


class TaskType(models.Model):
    task = models.ForeignKey('Task', related_name='types_tasks', on_delete=models.CASCADE, )
    type = models.ForeignKey('Type', related_name='tasks_types', on_delete=models.CASCADE, )

issue_tracker/webapp/models/projects.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse

from accounts.views import User


class Project(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    start_date = models.DateField()
    end_date = models.DateField(blank=True, null=True)
    user = models.ForeignKey(
        get_user_model(),
        related_name="projects",
        on_delete=models.SET_DEFAULT,
        default=1
    )

    def get_absolute_url(self):
        return reverse('webapp:project-detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Project'
        verbose_name_plural = 'Projects'

issue_tracker/webapp/models/statuses.py
from django.db import models


class Status(models.Model):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Statuses'

issue_tracker/webapp/models/tasks.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse

from .projects import Project
from .statuses import Status
from .types import Type


class Task(models.Model):
    summary = models.CharField(max_length=100)
    description = models.TextField(blank=True, null=True)
    status = models.ForeignKey(Status, on_delete=models.PROTECT)
    type = models.ManyToManyField(
        Type,
        related_name="tasks",
        verbose_name="Типы",
        blank=True,
        through='TaskType',
        through_fields=("task", "type"),
    )
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(
        get_user_model(),
        related_name="tasks",
        on_delete=models.SET_DEFAULT,
        default=1
    )

    def __str__(self):
        return self.summary

    def get_absolute_url(self):
        return reverse("webapp:task_detail", kwargs={"pk": self.pk})
    class Meta:
        verbose_name = 'Task'
        verbose_name_plural = 'Tasks'


class TaskType(models.Model):
    task = models.ForeignKey('Task', on_delete=models.CASCADE)
    type = models.ForeignKey('Type', on_delete=models.CASCADE)

issue_tracker/webapp/models/types.py
from django.db import models


class Type(models.Model):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name

issue_tracker/webapp/forms.py
from django import forms
from .models import Task


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = '__all__'
        widgets = {
            'status': forms.Select(),
            'type': forms.CheckboxSelectMultiple(),
        }

issue_tracker/webapp/forms/project_form.py
from django import forms
from ..models import Project


class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = '__all__'

issue_tracker/webapp/forms/search_form.py
from django import forms


class SearchForm(forms.Form):
    search = forms.CharField(max_length=50, label='Поиск', required=False)

issue_tracker/webapp/forms/task_form.py
from django import forms
from ..models import Task


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['summary', 'description', 'status', 'type']
        widgets = {
            'status': forms.Select(),
            'type': forms.CheckboxSelectMultiple(),
        }

issue_tracker/webapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import TemplateView, FormView, ListView

from .models import Task
from .forms import TaskForm


class TaskListView(ListView):
    model = Task
    template_name = 'home.html'


class TaskDetailView(TemplateView):
    template_name = "detail_task.html"

    def dispatch(self, request, *args, **kwargs):
        self.task = get_object_or_404(Task, pk=self.kwargs['pk'])
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['task'] = self.task
        return context


class TaskCreateView(FormView):
    template_name = "add_task.html"
    form_class = TaskForm

    def form_valid(self, form):
        task = form.save()
        return redirect("detail_task", pk=task.pk)


class TaskUpdateView(FormView):
    template_name = "update_task.html"
    form_class = TaskForm

    def dispatch(self, request, *args, **kwargs):
        self.task = self.get_object()
        return super().dispatch(request, *args, **kwargs)

    def get_object(self):
        return get_object_or_404(Task, pk=self.kwargs.get("pk"))

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['instance'] = self.task
        return kwargs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['task'] = self.task
        return context

    def form_valid(self, form):
        form.save()
        return redirect("detail_task", pk=self.task.pk)

    def form_invalid(self, form):
        return self.render_to_response(self.get_context_data(form=form))


class TaskDeleteView(TemplateView):
    template_name = "delete_task.html"

    def post(self, request, *args, **kwargs):
        task = get_object_or_404(Task, pk=self.kwargs['pk'])
        if request.method == 'POST':
            task.delete()
            return redirect('task_list')
        return render(request, 'delete_task.html', {'task': task})

issue_tracker/webapp/views/projects.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.db.models import Q
from django.urls import reverse_lazy
from django.utils.http import urlencode
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from ..forms import SearchForm, ProjectForm
from ..models import Task
from ..models.projects import Project


class ProjectListView(ListView):
    model = Project
    template_name = "projects/index.html"
    context_object_name = "projects"
    paginate_by = 5

    def dispatch(self, request, *args, **kwargs):
        self.form = self.get_form()
        self.search_value = self.get_search_value()
        return super().dispatch(request, *args, **kwargs)

    def get_form(self):
        return SearchForm(self.request.GET)

    def get_search_value(self):
        form = self.form
        if form.is_valid():
            return form.cleaned_data['search']

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.search_value:
            queryset = queryset.filter(
                Q(name__contains=self.search_value) | Q(description__contains=self.search_value)
            )
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["search_form"] = self.form
        if self.search_value:
            context["search"] = urlencode({"search": self.search_value})
            context["search_value"] = self.search_value
        return context


class ProjectDetailView(DetailView):
    model = Project
    template_name = "projects/project_detail.html"
    context_object_name = 'project'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tasks'] = Task.objects.filter(project=self.object)
        return context


class ProjectCreateView(LoginRequiredMixin, CreateView):
    model = Project
    form_class = ProjectForm
    template_name = "projects/project_add.html"
    success_url = reverse_lazy('project_list')


class ProjectUpdateView(PermissionRequiredMixin, LoginRequiredMixin, UpdateView):
    model = Project
    form_class = ProjectForm
    template_name = "projects/project_update.html"
    success_url = reverse_lazy('project_list')
    permission_required = "webapp.change_project"

    def has_permission(self):
        # return self.request.user.groups.filter(name="moderators").exists()
        return super().has_permission() or self.request.user == self.get_object().user


class ProjectDeleteView(PermissionRequiredMixin, LoginRequiredMixin, DeleteView):
    model = Project
    success_url = reverse_lazy('project_list')
    template_name = "projects/project_confirm_delete.html"
    permission_required = "webapp.delete_project"

    def has_permission(self):
        return super().has_permission() or self.request.user == self.get_object().user

issue_tracker/webapp/views/tasks.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import TemplateView, ListView, CreateView, DeleteView, UpdateView

from ..models import Task, Project
from ..forms import TaskForm


class TaskListView(ListView):
    model = Task
    template_name = 'tasks/home.html'


class TaskDetailView(TemplateView):
    template_name = "tasks/detail_task.html"

    def dispatch(self, request, *args, **kwargs):
        self.task = get_object_or_404(Task, pk=self.kwargs['pk'])
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['task'] = self.task
        return context


class TaskCreateView(LoginRequiredMixin, CreateView):
    template_name = "tasks/add_task.html"
    form_class = TaskForm

    def form_valid(self, form):
        project = get_object_or_404(Project, pk=self.kwargs['pk'])
        task = form.save(commit=False)
        task.project = project
        task.save()
        return redirect("webapp:project_detail", pk=self.kwargs['pk'])


class TaskUpdateView(PermissionRequiredMixin, LoginRequiredMixin, UpdateView):
    model = Task
    form_class = TaskForm
    template_name = "tasks/update_task.html"
    context_object_name = 'task'
    permission_required = "webapp.change_task"

    def get_success_url(self):
        return reverse_lazy('webapp:project_detail', kwargs={'pk': self.object.project.pk})

    def has_permission(self):
        # return self.request.user.groups.filter(name="moderators").exists()
        return super().has_permission() or self.request.user == self.get_object().user


class TaskDeleteView(PermissionRequiredMixin, LoginRequiredMixin, DeleteView):
    model = Task
    template_name = "tasks/delete_task.html"
    context_object_name = 'task'
    permission_required = "webapp.delete_task"

    def get_success_url(self):
        return reverse_lazy('webapp:project_detail', kwargs={'pk': self.object.project.pk})

    def has_permission(self):
        return super().has_permission() or self.request.user == self.get_object().user

issue_tracker/webapp/templates/projects/index.html
{% extends 'base.html' %}
{% block content %}
        <h1>Project List</h1>

        <a href="{% url 'webapp:project_add' %}" class="btn btn-primary">Add Project</a>
        <table class="table">
            <tbody>
            {% if projects %}
                <ul>
                {% for project in projects %}
                    <div class="col-12 col-md-6 col-lg-4">
                        <div class="card mt-3 text-center" style="width: 18rem;">
                            <div class="card-body">
                                    <a class="card-title" href="{% url 'webapp:project_detail' project.pk %}" class="text-decoration-none">{{ project.name }}
                                    </a>
                                    <br>
                                    {{ project.start_date }}
                                    <br>
                                    {% if perms.webapp.change_project or request.user == project.user %}
                                        <a href="{% url 'webapp:project_update' project.pk %}" class="btn"><i class="fa-solid fa-pen-to-square"></i></a>
                                    {% endif %}
                                    {% if perms.webapp.change_project or request.user == project.user %}
                                        <form action="{% url 'webapp:project_delete' project.pk %}" method="post" style="display:inline;">
                                    {% endif %}        
                                        {% csrf_token %}
                                        {% if perms.webapp.change_project or request.user == project.user %}
                                            <a href="{% url 'webapp:project_delete' project.pk %}" class="btn">
                                            <i class="fa-solid fa-trash"></i>
                                            </a>
                                        {% endif %}
                                    </form>
                            </div>
                        </div>
                    </div>

                {% endfor %}
            {% if is_paginated %}
                {% include "partial/pagination.html" %}
            {% endif %}
    {% else %}
        <p>No projects found</p>
    {% endif %}
{% endblock %}

issue_tracker/webapp/templates/projects/project_add.html
{% extends 'base.html' %}
{% block content %}
    <title>Add Task</title>
    
    <body>
        <div class="container">
            <h1>Add Project</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Save</button>
            </form>
            <a href="{% url 'webapp:project_list' %}" class="btn btn-secondary">Back to Task List</a>
        </div>
    </body>
{% endblock %}

issue_tracker/webapp/templates/projects/project_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
<h2>Delete</h2>
<p>Sure wanna delete this?</p>
<form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Удалить</button>
</form>
{% endblock %}

issue_tracker/webapp/templates/projects/project_detail.html
{% extends 'base.html' %}
{% block content %}
    <title>Project Detail</title>
<body>
    <h1>{{ project.name }}</h1>
    <p>{{ project.description }}</p>
    <p>Start Date: {{ project.start_date }}</p>
    <p>End Date: {{ project.end_date }}</p>
    <a href="{% url 'webapp:project_update' project.pk %}" class="btn btn-primary">Edit Project</a>
    <a href="{% url 'webapp:project_delete' project.pk %}" class="btn btn-primary">Delete Project</a>

    <h2>Tasks</h2>
    <a href="{% url 'webapp:add_task' project.pk %}" class="btn btn-primary">Add Task</a>
        <ul>
            {% for task in tasks %}
            <div class="col-12 col-md-6 col-lg-4">
                <div class="card mt-3 text-center" style="width: 18rem;">
                    <div class="card-body">
                        <tr>
                            <td><a href="{% url 'webapp:detail_task' task.pk %}"
                                   class="text-decoration-none card-title">{{ task.summary }}
                            </a></td>
                            <br>
                            <td>{{ task.status }}</td>
                            <br>
                            <td>{% for type in task.type.all %}
                                {{ type.name }}
                                {% endfor %}
                            </td>
                            <br>
                            <td><a href="{% url 'webapp:update_task' task.pk %}" class="btn"><i
                                    class="fa-solid fa-pen-to-square"></i></a>
                                <form action="{% url 'webapp:delete_task' task.pk %}" method="post" style="display:inline;">
                                    {% csrf_token %}
                                    <a href="{% url 'webapp:delete_task' task.pk %}" class="btn">
                                        <i class="fa-solid fa-trash"></i>
                                    </a>
                                </form>
                            </td>
                        </tr>
                    </div>
                </div>
            </div>
                
    {% empty %}
        <p>No tasks found for this project</p>
                {% endfor %}
        </ul>
</body>
{% endblock %}

issue_tracker/webapp/templates/projects/project_update.html
{% extends 'base.html' %}
{% block content %}
<h1>Project update</h1>

<form action="" method="post">
    {% include 'partial/form_task.html' with button_text='Update' %}

</form>
{% endblock %}